.PHONY: build start stop

# Default target
build:
    docker-compose build
    docker-compose up -d

start: ## Start Docker Compose
    docker-compose up -d

stop: ## Stop Docker Compose
    docker-compose down
